# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PegelOnlineDisplayer
                                 A QGIS plugin
 Show information about different measurement stations
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-08-22
        copyright            : (C) 2019 by Benedikt Lüken-Winkels
        email                : s4beluek@uni-trier.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PegelOnlineDisplayer class from file PegelOnlineDisplayer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pegel_online_displayer import PegelOnlineDisplayer
    return PegelOnlineDisplayer(iface)
